apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: cherryapp
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: cherryapp-warehouse
    sources:
      direct: true
