apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: cherryapp
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: cherryapp-warehouse
      sources:
        stages:
          - staging
