apiVersion: kargo.akuity.io/v1alpha1
kind: Watcher
metadata:
  name: myapp-watcher
  namespace: kargo
spec:
  subscriptions:
    repos:
      - repoURL: https://github.com/benitha200/infra-cherry-app.git
        commit: latest
  stageRefs:
    - name: dev
    - name: staging
    - name: prod
