# argo/app-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/benitha200/infra-cherry-app.git
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - ../../environments/dev/frontend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/benitha200/infra-cherry-app.git
    targetRevision: main
    path: infra-cherry-app/backend
    helm:
      valueFiles:
        - ../../environments/dev/backend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/benitha200/infra-cherry-app.git
    targetRevision: main
    path: infra-cherry-app/mysql
    helm:
      valueFiles:
        - ../../environments/dev/mysql-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

